set to original ci

diff --git a/.github/workflows/automated-tests.yml b/.github/workflows/automated-tests.yml
--- a/.github/workflows/automated-tests.yml
+++ b/.github/workflows/automated-tests.yml
@@ -1,6 +1,6 @@
 name: "Automated tests"
 on:
-  workflow_dispatch:
+  push:
     branches:
       - "develop"
       - "v2.[5-9].x-release"
@@ -86,8 +86,8 @@ jobs:
           echo "CACHE_KEY_FILES=$(echo '${{ matrix.cache-files-list }} '$BUILD_DIRS' .gitlab-ci.yml build/deb-helper.sh' | xargs -n1 git log -1 --format=%h -- | tr '\n' '-' | sed 's/-$//')" >> $GITHUB_ENV
           echo "CACHE_KEY_URLS=$(echo '${{ matrix.cache-urls-list }}' | xargs -r -n 1 curl -Is | grep -i 'Last-Modified' | md5sum | cut -c1-10)" >> $GITHUB_ENV
           cat bigbluebutton-config/bigbluebutton-release >> $GITHUB_ENV
-          echo "FORCE_GIT_REV=0" >> $GITHUB_ENV
-          echo "FORCE_COMMIT_DATE=0" >> $GITHUB_ENV
+          echo "FORCE_GIT_REV=0" >> $GITHUB_ENV #used by setup.sh
+          echo "FORCE_COMMIT_DATE=0" >> $GITHUB_ENV #used by setup.sh
       - name: Handle cache
         if: matrix.cache-files-list != ''
         id: cache-action
@@ -255,7 +255,9 @@ jobs:
         run: |
           sudo sh -c '
           apt --purge -y remove apache2-bin
-          apt-mark hold firefox
+          apt-mark hold firefox #hold ff as bbb-install frequently stuck at `Installing the firefox snap`
+
+          #bbb-webrtc-sfu: removes the special scheduling policies
           mkdir -p /etc/systemd/system/bbb-webrtc-sfu.service.d/
           tee /etc/systemd/system/bbb-webrtc-sfu.service.d/override.conf > /dev/null <<EOL
           [Service]
@@ -263,15 +265,30 @@ jobs:
           Nice=19
           EOL
           systemctl daemon-reload
+
+          #Install Sipp for dial-in tests
           apt install -y pkg-config dh-autoreconf ncurses-dev build-essential libssl-dev libpcap-dev libncurses5-dev libsctp-dev lksctp-tools cmake
           git clone --recurse-submodules https://github.com/SIPp/sipp.git /opt/sipp
           cd /opt/sipp
-          git checkout 4682fdba2b63007f13a632c6eb06f0ece84cb7df
+          git checkout 4682fdba2b63007f13a632c6eb06f0ece84cb7df #Set an old commit as the current code is not working
           cmake . -DUSE_SSL=1 -DUSE_SCTP=1 -DUSE_PCAP=1 -DUSE_GSL=1
           make
           sudo make install
           rm -r /opt/sipp/gtest
           rm -r /opt/sipp/src
+
+          # Set dial plan for internal calls
+          mkdir -p /opt/freeswitch/conf/dialplan/public/
+          cat << EOF > "/opt/freeswitch/conf/dialplan/public/bbb_sip.xml"
+          <include>
+            <extension name="bbb_sp_call" continue="true">
+                <condition field="network_addr" expression="\${domain}" break="on-false">
+                    <action application="set" data="bbb_authorized=true"/>
+                    <action application="transfer" data="\${destination_number} XML default"/>
+                </condition>
+            </extension>
+          </include>
+          EOF
           '
       - name: Install BBB
         env:
@@ -284,33 +301,105 @@ jobs:
           wget -nv https://raw.githubusercontent.com/bigbluebutton/bbb-install/v3.0.x-release/bbb-install.sh -O bbb-install.sh
           sed -i "s|> /etc/apt/sources.list.d/bigbluebutton.list||g" bbb-install.sh
           chmod +x bbb-install.sh
+
           COMMAND="./bbb-install.sh -v jammy-30-dev -s bbb-ci.test -j -d /certs/"
-          TIMEOUT=1500
+          TIMEOUT=1500  # 25 minutes
           MAX_RETRIES=3
           RETRY_INTERVAL=60
           RETRY_COUNT=0
           SUCCESS=0
+
           while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
+            echo "Attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES to install BBB..."
+
+            # Run the command with timeout and handle its exit code
+            # Capture both stdout and stderr
+            COMMAND_EXIT_CODE=0
             timeout $TIMEOUT $COMMAND || COMMAND_EXIT_CODE=$?
+
             if [[ $COMMAND_EXIT_CODE -eq 0 ]]; then
               SUCCESS=1
               break
             elif [[ $COMMAND_EXIT_CODE -eq 124 ]]; then
-              echo "Retrying..."
+              echo "Installation timed out after ${TIMEOUT} seconds. Retrying..."
             else
-              echo "Retrying..."
+              echo "Installation failed with exit code $COMMAND_EXIT_CODE"
+              echo "Retrying installation within $RETRY_INTERVAL seconds..."
               sleep $RETRY_INTERVAL
             fi
+
+            echo "Check if there is some process still locking:1"
+            ps aux | grep -E 'dpkg|apt'
+
+            echo "Stop any ongoing processes related to apt-get or dpkg that might be stuck"
+            # Use -q to suppress "no process found" messages
+            # Kill any apt-get or dpkg processes that might be hanging
+            killall -9 -q apt-get || true
+            killall -9 -q dpkg || true
+
+            echo "Remove the lock files that may have been left behind"
+            # Group lock file removal for better readability
+            rm -f /var/lib/dpkg/lock-frontend
+            rm -f /var/lib/dpkg/lock
+            rm -f /var/cache/apt/archives/lock
+            rm -f /var/cache/debconf/config.dat
+
+            echo "Reconfigure the package manager"
+            dpkg --configure -a
+
+            echo "Clean up any partially installed packages"
+            apt-get clean
+            apt-get autoremove
+
+            echo "Check if there is some process still locking:2"
+            ps aux | grep -E 'dpkg|apt'
+
             RETRY_COUNT=$((RETRY_COUNT + 1))
           done
+
           if [[ $SUCCESS -eq 0 ]]; then
-            echo "All attempts failed."
+            echo "All attempts to install BBB failed."
             exit 1
           fi
+
+          bbb-conf --salt bbbci
+          sed -i "s/\"minify\": true,/\"minify\": false,/" /usr/share/etherpad-lite/settings.json
+          sed -i "s/\"loglevel\": \"INFO\"/\"loglevel\": \"DEBUG\"/" /usr/share/etherpad-lite/settings.json
+          sed -i "s/\"level\": \"info\"/\"level\": \"debug\"/" /usr/local/bigbluebutton/bbb-pads/config/settings.json
+          sed -i "s/exports.DEBUG = false/exports.DEBUG = true/" /usr/local/bigbluebutton/bbb-graphql-actions/config.js
+          sudo yq e -i '.log_level = "TRACE"' /usr/share/bbb-graphql-middleware/config.yml
+          echo "HASURA_GRAPHQL_LOG_LEVEL=debug" | tee -a /etc/bigbluebutton/bbb-graphql-server.env
+          cat > /etc/bigbluebutton/bbb-conf/apply-config.sh << HERE
+          #!/bin/bash
+
+          # Pull in the helper functions for configuring BigBlueButton
+          source /etc/bigbluebutton/bbb-conf/apply-lib.sh
+
+          # Available configuration options
+
+          enableHTML5ClientLog
+          #enableUFWRules
+
+          HERE
+          chmod +x /etc/bigbluebutton/bbb-conf/apply-config.sh
+          bbb-conf --restart
           EOF
-      - name: Install strace
-        run: sudo apt-get update && sudo apt-get install -y strace
-      - name: Run tests with strace
+      - name: List systemctl services
+        timeout-minutes: 1
+        run: |
+          sudo -i <<EOF
+          systemctl --type=service --state=running,exited,failed --all --no-pager --no-legend
+          EOF
+      - name: Install test dependencies
+        working-directory: ./bigbluebutton-tests/playwright
+        timeout-minutes: 25
+        run: |
+          sh -c '
+          npm ci
+          npx playwright install-deps
+          npx playwright install
+          '
+      - name: Run tests
         working-directory: ./bigbluebutton-tests/playwright
         timeout-minutes: 25
         env:
@@ -318,15 +407,75 @@ jobs:
           ACTIONS_RUNNER_DEBUG: true
           BBB_URL: https://bbb-ci.test/bigbluebutton/api
           BBB_SECRET: bbbci
+        run: npm run test-chromium-ci -- --shard=${{ env.shard }}
+      - name: Run Firefox tests
+        working-directory: ./bigbluebutton-tests/playwright
+        if: |
+          contains(github.event.pull_request.labels.*.name, 'test Firefox') ||
+          contains(github.event.pull_request.labels.*.name, 'Test Firefox')
+        env:
+          NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/bbb-dev/bbb-dev-ca.crt
+          ACTIONS_RUNNER_DEBUG: true
+          BBB_URL: https://bbb-ci.test/bigbluebutton/api
+          BBB_SECRET: bbbci
+        # patch playwright's firefox so that it uses the system's root certificate authority
         run: |
-          strace -ff -o ./strace_log_$(date +%Y%m%d%H%M%S).txt npm run test-chromium-ci -- --shard=${{ env.shard }}
-      
-      - name: Upload strace logs
+          sh -c '
+          find $HOME/.cache/ms-playwright -name libnssckbi.so -exec rm {} \; -exec ln -s /usr/lib/x86_64-linux-gnu/pkcs11/p11-kit-trust.so {} \;
+          npm run test-firefox-ci -- --shard=${{ env.shard }}
+          '
+      - if: always()
+        name: Upload blob report to GitHub Actions Artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: strace-logs
-          path: ./strace_log_*.txt
-          
+          name: blob-report-${{ matrix.shard }}
+          path: bigbluebutton-tests/playwright/blob-report
+      - if: always()
+        name: Generate the shard HTML report from blob report
+        shell: bash
+        working-directory: ./bigbluebutton-tests/playwright
+        run: npx playwright merge-reports --reporter html ./blob-report
+      - if: always()
+        name: Upload shard HTML report to GitHub Actions Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-report_shard-${{ matrix.shard }}
+          path: bigbluebutton-tests/playwright/playwright-report
+      - if: failure()
+        name: Prepare artifacts (configs and logs)
+        run: |
+          sudo -i <<EOF
+          mkdir configs
+          cp /etc/haproxy/haproxy.cfg configs/haproxy.cfg
+          touch /etc/bigbluebutton/turn-stun-servers.xml
+          cp /etc/bigbluebutton/turn-stun-servers.xml configs/turn-stun-servers.xml
+          cp /opt/freeswitch/etc/freeswitch/vars.xml configs/freeswitch_vars.xml
+          cp /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml configs/freeswitch_sip_profiles_external.xml
+          cp /etc/bigbluebutton/bbb-apps-akka.conf configs/bbb-apps-akka.conf
+          cp /etc/bigbluebutton/bbb-fsesl-akka.conf configs/bbb-fsesl-akka.conf
+          cp /etc/bigbluebutton/bbb-html5.yml configs/bbb-html5.yml
+          cp /etc/bigbluebutton/bbb-web.properties configs/bbb-web.properties
+          cp /etc/bigbluebutton/bigbluebutton-release configs/bigbluebutton-release
+          cp /etc/bigbluebutton/turn-stun-servers.xml configs/turn-stun-servers.xml
+          cp /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml configs/bbb-webrtc-sfu-default.yml
+          cp /etc/bbb-webrtc-recorder/bbb-webrtc-recorder.yml configs/bbb-webrtc-recorder-default.yml
+          cp /usr/share/bigbluebutton/nginx/sip.nginx configs/nginx_sip.nginx
+          cp /etc/hosts /configs/hosts
+          mv configs /home/runner/work/bigbluebutton/bigbluebutton/configs
+          chmod a+r -R /home/runner/work/bigbluebutton/bigbluebutton/configs
+          bbb-conf --zip
+          ls -t /root/*.tar.gz | head -1 | xargs -I '{}' cp '{}' /home/runner/work/bigbluebutton/bigbluebutton/bbb-logs.tar.gz
+          EOF
+      - if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: bbb-configs-${{ env.MATRIX_SHARD_UNDERSCORED }}
+          path: configs
+      - if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: bbb-logs-${{ env.MATRIX_SHARD_UNDERSCORED }}
+          path: ./bbb-logs.tar.gz
   upload-report:
     if: always() && !contains(github.event.head_commit.message, 'Merge pull request')
     needs: install-and-run-tests
@@ -338,6 +487,11 @@ jobs:
       - name: Merge and upload the blob reports
         if: ${{ env.hasReportData }}
         uses: ./.github/actions/merge-and-upload-blob-reports
+      - name: Remove unnecessary artifact
+        uses: geekyeggo/delete-artifact@v5
+        with:
+          name: all-blob-reports
+          failOnError: false
       - name: Write PR data for auto-comment
         if: github.event_name == 'pull_request'
         working-directory: ./
